"""
V3 PURE - NO V2 LOGIC ALLOWED

Type definitions for V3 linear timeline architecture.

CRITICAL RULES:
- Use minuteOffset (int) NOT heure_debut/heure_fin (str)
- TaskV3 is the ONLY task type in V3
- All time calculations work in minutes from planningStartTime
- Convert to absolute times ONLY for display (final step)
"""

from typing import TypedDict, List, Optional


class TaskV3(TypedDict, total=False):
    """
    V3 Task with linear timeline (minuteOffset-based).

    REQUIRED fields:
        minuteOffset: Minutes from planningStartTime (0 = start time)
        duration: Duration in minutes
        type: Task type (POMODORO, PAUSE, CALIN, CLOPE, PLANNED)
        taskId: Original task ID from CSV
        taskName: Display name
        isFixed: True if non-draggable (planned tasks)

    OPTIONAL fields:
        pomodoroIndex: Index for pomodoro sequences (1, 2, 3...)
        pomodoroTotal: Total pomodoros for parent task
        autoGenerated: True for auto-inserted calins/clopes
        rescheduled: True if planned task was moved due to collision
    """
    # REQUIRED (enforced by total=False and explicit marking)
    minuteOffset: int        # ✅ V3 CORE - Forces linear timeline
    duration: int            # Duration in minutes
    type: str                # POMODORO, PAUSE, CALIN, CLOPE, PLANNED
    taskId: str              # Original CSV ID
    taskName: str            # Display name
    isFixed: bool            # True = non-draggable

    # OPTIONAL (for specific task types)
    pomodoroIndex: int       # 1, 2, 3... (POMODORO only)
    pomodoroTotal: int       # Total count (POMODORO only)
    autoGenerated: bool      # True for CALIN/CLOPE
    rescheduled: bool        # True if PLANNED task moved


class Obstacle(TypedDict):
    """
    Linear obstacle (temps mort) in timeline.

    Obstacles block time slots and force tasks to skip past them.
    Times are in minutes from planningStartTime.
    """
    startMinute: int         # Start time (minutes from planningStart)
    endMinute: int           # End time (minutes from planningStart)
    type: str                # Always 'temps_mort'
    originalData: dict       # Original CSV row data


class Timeline(TypedDict):
    """
    Complete planning timeline with tasks and obstacles.

    This is the main data structure returned by rebuildTimeline().
    """
    planningStartTime: str   # ISO datetime (YYYY-MM-DDTHH:MM:SS)
    tasks: List[TaskV3]      # All tasks with calculated minuteOffsets
    obstacles: List[Obstacle]  # All obstacles (temps morts)


# Type aliases for clarity
TaskList = List[TaskV3]
ObstacleList = List[Obstacle]


# Constants for task types (prevents typos)
class TaskType:
    """Task type constants - use these instead of raw strings"""
    POMODORO = "POMODORO"
    PAUSE = "PAUSE"
    CALIN = "CALIN"
    CLOPE = "CLOPE"
    PLANNED = "PLANNED"
    RECURRENT = "RECURRENT"


class ObstacleType:
    """Obstacle type constants"""
    TEMPS_MORT = "temps_mort"


# Validation helpers
def is_valid_task_v3(task: dict) -> bool:
    """
    Check if dict has required TaskV3 fields.

    Used for runtime validation in data_loader_v3.py
    """
    required_fields = ['minuteOffset', 'duration', 'type', 'taskId', 'taskName', 'isFixed']
    return all(field in task for field in required_fields)


def create_task_v3(
    minute_offset: int,
    duration: int,
    task_type: str,
    task_id: str,
    task_name: str,
    is_fixed: bool = False,
    **kwargs
) -> TaskV3:
    """
    Factory function to create TaskV3 with validation.

    Example:
        task = create_task_v3(
            minute_offset=0,
            duration=25,
            task_type=TaskType.POMODORO,
            task_id="TASK001",
            task_name="Implement feature X",
            pomodoroIndex=1,
            pomodoroTotal=3
        )
    """
    task: TaskV3 = {
        'minuteOffset': minute_offset,
        'duration': duration,
        'type': task_type,
        'taskId': task_id,
        'taskName': task_name,
        'isFixed': is_fixed,
    }

    # Add optional fields
    for key in ['pomodoroIndex', 'pomodoroTotal', 'autoGenerated', 'rescheduled']:
        if key in kwargs:
            task[key] = kwargs[key]  # type: ignore

    return task


def create_obstacle(
    start_minute: int,
    end_minute: int,
    original_data: dict
) -> Obstacle:
    """
    Factory function to create Obstacle.

    Example:
        obstacle = create_obstacle(
            start_minute=120,
            end_minute=180,
            original_data={'nom': 'Réunion', 'heure_debut': '08:00'}
        )
    """
    return {
        'startMinute': start_minute,
        'endMinute': end_minute,
        'type': ObstacleType.TEMPS_MORT,
        'originalData': original_data
    }
